config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :courses
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      resources :courses do
        resources :tasks
      end
      get :my_courses, to: "courses#my_courses"
    end
    post "/graphql", to: "graphql#execute"
    post :auth, to: "authentication#authenticate"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root to: "courses#index"
  get :home, to: "home#index"
  resources :carts do
    member do
      post :checkout_notification
      get :remove_discount
    end
  end
  resources :cart_items, only: [:destroy]
  resources :courses do
    # courses/:id/subscribe
    member do
      get :subscribe
      get :add_to_cart
    end
    resources :tasks, only: [:show] do
      member do
        put :complete
      end
    end
    
    resources :reviews, only: [:create, :destroy]
  end
  
  get "/my_courses", to: "courses#my_courses"
  get "/my_cart", to: "carts#index"
  get :checkout, to: "carts#checkout"
  post :get_discount, to: "carts#get_discount"
  post "/payment_notification", to: "courses#payment_notification"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_devise_message.html.erb
<% unless resource.errors.empty? %>
  <script>
    <% resource.errors.full_messages.each do |msg| %>
      toastr['error']('<%= msg %>');
    <% end %>
  </script>  
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Kampus RoR</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Kampus RoR
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "My Profile", edit_user_registration_path %></li>
  <li><%= link_to "My Courses", my_courses_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
</ul>
<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to "My Profile", edit_user_registration_path %></li>
  <li><%= link_to "My Courses", my_courses_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
</ul>

<header>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Kampus RoR</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Courses", courses_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <li>
              <%= link_to my_cart_path do %>
                My Cart
                <% if current_cart.cart_items.length > 0 %>
                  <span class="new badge"><%= current_cart.cart_items.length %></span>
                <% end %>
              <% end %>
            </li>
            <!-- Dropdown Trigger -->
            <li>
              <a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
                <%= image_tag avatar_url(current_user), class: "circle responsevie_img" %>
                <%= current_user.name %><i class="material-icons right">arrow_drop_down</i>
              </a>
            </li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "Courses", courses_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<% if @show_search_bar %>
  <div class="container">
    <div class="row">
      <div class="col s12">
        <%= form_tag courses_path, method: :get do %>
          <div class="input-field">
            <%= text_field_tag :search, params[:search], type: "search", placeholder: "Search Course", style: 'padding-left: 4rem;  width: calc(100% - 4rem)' %>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>  

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |f| %>
      <% type = f[0].gsub('notice', 'info').gsub('alert', 'error') %>
      toastr['<%= type %>']('<%= f[1]%>');
    <% end %>
  </script>  
<% end %>