config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end

  namespace :api do
    scope module: :v2, constraints: ApiVersion.new('v2') do
      resources :courses
    end
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      resources :courses do
        resources :tasks
      end
      get :my_courses, to: "courses#my_courses"
    end
    post "/graphql", to: "graphql#execute"
    post :auth, to: "authentication#authenticate"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root to: "courses#index"
  get :home, to: "home#index"
  resources :carts do
    member do
      post :checkout_notification
      get :remove_discount
    end
  end
  resources :cart_items, only: [:destroy]
  resources :courses do
    # courses/:id/subscribe
    member do
      get :subscribe
      get :add_to_cart
    end
    resources :tasks, only: [:show] do
      member do
        put :complete
      end
    end
    
    resources :reviews, only: [:create, :destroy]
  end
  
  get "/my_courses", to: "courses#my_courses"
  get "/my_cart", to: "carts#index"
  get :checkout, to: "carts#checkout"
  post :get_discount, to: "carts#get_discount"
  post "/payment_notification", to: "courses#payment_notification"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  
  def add_item(course_id)
    course = Course.find(course_id)
    cart_items.find_or_create_by(course_id: course.id, sub_total: course.price)
    update_total
  end
  
  def remove_item(cart_item_id)
    item = cart_items.find(cart_item_id)
    item.destroy
    update_total
  end
  
  def update_total
    self.total = cart_items.sum(:sub_total)
    save
  end
  
  def checkout_url
    params = {
      :business => Rails.application.secrets.paypal_email,
      :cmd => "_cart",
      :upload => 1,
      :notify_url => "#{Rails.application.secrets.site_url}/carts/#{self.id}/checkout_notification",
      :return => "#{Rails.application.secrets.site_url}/my_courses"
    }
    cart_items.each_with_index do |item, index|
      i = index + 1
      params["item_name_#{i}"] = item.course.title
      params["item_number_#{i}"] = item.course_id
      params["amount_#{i}"] = item.sub_total
    end
    "#{Rails.application.secrets.paypal_url}/cgi-bin/webscr?" + params.to_query
  end
  
  def process_payment(params)
    if params["payment_status"] == "Completed"
      cart_items.each_with_index do |item, index|
        i = index + 1
        if item.sub_total.to_f == params["mc_gross_#{i}"].to_f
          Subscription.find_or_create_by(user: user, course_id: item.course_id, payment_status: "Completed", active: true)
        end
      end
      self.completed = true
      save
    end
  end
  
  def check_discount(code)
    discount_code = DiscountCode.find_by(code: code)
    if discount_code && discount_code.active? && discount_code.expired_date > Date.today
      self.discount_code = code
      cart_items.each do |item|
        item.update_attributes(sub_total: discount_code.discount_total(item.sub_total))
      end
      self.total = discount_code.discount_total(total)
      save
    else
      false
    end
  end
  
  def remove_discount
    self.discount_code = nil
    cart_items.each do |item|
      item.update_attributes(sub_total: item.course.price)
    end
    update_total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, except: [:checkout_notification]
  skip_before_action :show_search_bar
  protect_from_forgery except: [:checkout_notification]
   
  def index
    @cart = current_cart
  end
  
  def checkout
    redirect_to current_cart.checkout_url
  end
  
  def checkout_notification
    if PayPal::SDK::Core::API::IPN.valid?(request.raw_post) 
      @cart = Cart.find(params[:id])
      unless @cart.completed?
        @cart.process_payment(params)  
      end 
      head :ok
    else
      head :not_acceptable
    end
  end
  
  def get_discount
    @cart = current_cart
    if @cart.check_discount(params[:cart][:discount_code])
      redirect_to my_cart_path, notice: "Discount code added"
    else
      redirect_to my_cart_path, alert: "Discount code is invalid"
    end
  end
  
  def remove_discount
    current_cart.remove_discount
    redirect_to my_cart_path, notice: "Discount removed"
  end
end

app/views/carts/index.html.erb
<% if @cart.cart_items.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Course</th>
        <th>Price</th>
        <th>Action</th>
      </tr>  
    </thead>
    <tbody>
      <% @cart.cart_items.each do |item| %>
        <tr>
          <td><%= link_to item.course.title, item.course %></td>
          <td><%= number_to_currency item.sub_total %></td>
          <td><%= link_to "Remove", item, method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
      <% end %>  
    </tbody>
  </table>
  <p>
    <% if @cart.discount_code.present? %>
      Discount Code: <b><%= @cart.discount_code %></b> <%= link_to "Remove Discount", remove_discount_cart_path(@cart) %>
    <% else %>
      <%= form_for @cart, url: get_discount_path, method: :post do |f| %>
        <div class="input-field inline">
          <%= f.text_field :discount_code %>
          <%= f.submit "Apply Discount" %>
        </div>
      <% end %>
    <% end %>
  </p>
  <p>
    Total: <b><%= number_to_currency @cart.total %></b>
  </p>
  <%= link_to "Pay with paypal", checkout_path, class: "btn right" %>
<% else %>
  <p class="flow-text center">
    No items found in your cart.
  </p>
<% end %>